services:
  nodejs:
    image: vectra:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - ARANGO_URL=http://arangodb:8529
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
      - arangodb
      - ollama
