name: Build and Deploy Client

on:
  push:
    branches: [ main ]
    paths:
      - 'client/app/**'
      - '.github/workflows/client-deploy.yml'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          cd client/app
          npm install

      # Step 4: Build the project
      - name: Build the project
        run: |
          cd client/app
          npm run build

      # Step 5: Deploy to DigitalOcean
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            # Clean the Nginx web directory
            rm -rf /var/www/html/*
            
            # Copy built files to web directory
            cp -r client/app/dist/* /var/www/html/
            
            # Restart Nginx to serve new files
            sudo systemctl restart nginx 