name: Deploy Client

on:
  push:
    branches: [ main ]
    paths:
      - 'client/app/**'
      - '.github/workflows/client-deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build client assets
        run: |
          cd client/app
          npm install
          npm run build
          cd ../..

      - name: Deploy client to DigitalOcean
        uses: docker/ssh-action@v1
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            mkdir -p /var/www/html
          script_stop: false

      - name: Sync client assets
        run: |
          rsync -avz --delete \
            --exclude='.git' \
            --exclude='node_modules' \
            client/app/dist/ \
            ${{ secrets.DROPLET_USERNAME }}@${{ secrets.DROPLET_HOST }}:/var/www/html/

      - name: Restart Nginx
        uses: docker/ssh-action@v1
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: systemctl restart nginx 