name: Build and Deploy Client

on:
  push:
    branches: [ main ]
    paths:
      - 'client/app/**'
      - '.github/workflows/client-deploy.yml'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Deploy and build on DigitalOcean droplet
      - name: Deploy and build on DigitalOcean droplet
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            # Navigate to the project directory
            cd /opt/app/vectra
            
            # Pull the latest changes
            git pull origin main

            # Navigate to the client directory
            cd client/app
            
            # Install dependencies if needed
            npm install
            
            # Build the React application for production
            npm run build
            
            # Clean the Nginx web directory
            rm -rf /var/www/html/*
            
            # Copy built files to web directory
            cp -r dist/* /var/www/html/
            
            # Restart Nginx to serve new files
            sudo systemctl restart nginx 