name: Deploy Server

on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'
      - '.github/workflows/server-deploy.yml'

env:
  DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/vectra

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Node.js application
        uses: docker/build-push-action@v4
        with:
          context: ./server
          file: ./server/Dockerfile.prod
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}:latest

      - name: Deploy server to DigitalOcean
        uses: docker/ssh-action@v1
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd /opt/app
            docker pull ${{ env.DOCKER_IMAGE_NAME }}:latest
            docker-compose down
            docker-compose up -d 