name: Deploy Server

on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'
      - '.github/workflows/server-deploy.yml'

env:
  DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/vectra

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Node.js application
        uses: docker/build-push-action@v4
        with:
          context: ./server
          file: ./server/Dockerfile.prod
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}:latest
          cache-from: |
            type=registry,ref=${{ env.DOCKER_IMAGE_NAME }}:latest
            type=registry,ref=${{ env.DOCKER_IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_IMAGE_NAME }}:buildcache,mode=max

      - name: Deploy server to DigitalOcean
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd /opt/app/vectra
            git pull origin main
            docker pull ${{ env.DOCKER_IMAGE_NAME }}:latest
            docker-compose -f docker-compose.prod.yml down
            docker-compose -f docker-compose.prod.yml up -d